### ISSUE TITLE
Unable to install the package “orchaRd”

### ISSUE THREAD

**Issue by ZXX-NWAFU** [itchyshin/orchard_plot#11]
Neither online nor local download can be loaded into R studio

**Comment by itchyshin** [comment]
@ZXX-NWAFU - we have moved to new website now - check out

https://github.com/daniel1noble/orchaRd

**Comment by ZXX-NWAFU** [comment]
thank U the God Nakagawa，I admire you very much, you are the god of meta analysis, I hope to cooperate with you in the future





---- Replied Message ----
From Shinichi ***@***.***>Date 7/29/2022 08:34To ***@***.***>Cc New Zhu ***@***.***> ,
 ***@***.***>Subject Re: [itchyshin/orchard_plot] Unable to install the package “orchaRd” (Issue #11)

@ZXX-NWAFU - we have moved to new website now - check out
https://github.com/daniel1noble/orchaRd
