### ISSUE TITLE
Not able to update color in the plot

### ISSUE THREAD

**Issue by KontorErnestKissi** [itchyshin/orchard_plot#13]
Can you please help me update the color as the code below produces the plot but the color is not changed:

orchaRd::bubble_plot(
  BC_M1,
  mod = "Count",
  group = "Author",
  xlab = "Moderator",
  ylab = "Effect size",
  k = FALSE
) + scale_fill_manual(values = "blue") + 
    scale_colour_manual(values = "blue")

**Comment by itchyshin** [comment]
@KontorErnestKissi 

Please use our newer version - 

https://github.com/daniel1noble/orchaRd

https://daniel1noble.github.io/orchaRd/
