### ISSUE TITLE
name is a character string and ggplot sorts it alphabetically

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/orchard_plot#2]
We need to make this characters to a factor

**Comment by mlagisz** [comment]
I dont think this is resolved - when I run orchard_plot on my meta-regression model with an ordered moderator it keeps the correct order of levels in the created object p (I can see it in p$data), but when this object gets rendered graphically, the levels and associated data still get sorted and displayed alphabetically. This perhaps needs more testing?
