### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/orchard_plot#3]
@daniel1noble 

Why do you think this happens

Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/orchaRd/R/orchaRd.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1

**Comment by itchyshin** [comment]
@daniel1noble 

This error only happens if I use normal R but not happens if I use R Studio

Any ideas?

**Comment by daniel1noble** [comment]
@itchyshin Odd. Not sure. It works fine on my end on a fresh install. What is the background? Are you just trying to just load the library? Or using devtools? R v3.60 is my version of R

**Comment by mlagisz** [comment]
@daniel1noble e I was not able to download and install orchaRd from gitHub on Friday, but it worked again on Saturday. I use Rstudio 1.2.1335. R version 3.6.0 (2019-04-26). Platform: x86_64-apple-darwin15.6.0 (64-bit) under macOS Mojave 10.14.6.

**Comment by daniel1noble** [comment]
Odd @mlagisz . Maybe an internet issue? Working now?

**Comment by mlagisz** [comment]
yes, it works now @daniel1noble, the issue was last week but It seems to be fixed now, at least on Rstudio
