### ISSUE TITLE
Caterpillars

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/orchard_plot#5]
Make it possible to sort small to large and also large to small.

**Comment by scubetto** [comment]
Hi, I am experiencing some x axis scale issue. Both data and polygons are not clearly reported in the plot frame. I have tried by resatting the x axis scale but thinsg went even worse. Any idea? thanks.
![Caterpillars shoot density](https://github.com/itchyshin/orchard_plot/assets/140057827/34018a83-c5d7-4442-a5f9-61f926cc9558)

**Comment by itchyshin** [comment]
@scubetto  - you may need to adjust the size of the plot. X (log shoot density seems like extremely large by the way - also we move to https://github.com/daniel1noble/orchaRd
